server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: ansh
    password: ansh1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true