spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://anshg2003:Optiplex2160@cluster0.7y92qnp.mongodb.net/
      database: microservices
  config:
    import: optional:configserver:http://localhost:8085

server:
  port: 8083